/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idl;

import org.gradle.api.Project;
import org.gradle.api.Incubating;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
@Incubating
public class IdlPlugin implements Plugin<Project> {
    
    @Override
    public void apply(Project project) { 
        // Register a task
        project.getTasks().register("generateIdl", BuildTask.class);
        /*project.getTasks().create("buildIdl", Exec.class, task -> {
            task.setDescription("Generate code from IDL files");
            task.setGroup("IDL");
            task.executable("omniidl");
            task.args("-bcxx");
            task.args("-C", "output");
        });*/
    }
}
